language: c
compiler: gcc

os: linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake .
  - make

deploy:
  provider: releases
  api_key:
    secure: "iscNIeQwtkg/gf/4ChGnKN2CuknCAaPSMsvuVjlcBtjzQgzoU7htOeeNRQmJ2dzeBXymue2Zzd3rYZOTFsbOi76H3EgIyM3YEG1kzW05YQA2mDdhRt1yzOj43GE3qFbqn2NTNmQigGJBJWQeqT/gyhNLDTHQfy8vF6EU+jigZnv0i5xK6fW/Hc/2UJHWbKVplssqybOkWFIiQv4q7A8qk/Kfz2/cB6xtdkUy1k01jsu2toy+Qr7ySFn7E1fN4wRGbBuvR1Z+w+HVhWNGKpHN67z2LvSViWO2SS+A6Ef0/zE6z+4CouXeMuUBaEQY58snuEaZTzT9AQPu0VZ0KACJW7Ym7rr7P4/DfsNRCWORsdx6x9+tiYvP90C+b176Bky5Es+Xg/3fqJuCrXwWnv3VUzt6QZCqGE9M2EKZR05eyC6sPWyOo8qgQ7pWfgZhG9gmGmqiDL404xzA8Vn3R4f+uaMFm/9+M6UQQJGO98Cl+9GvAYIe3EJPNuS2ZchcO5SpYBtTLxTMe/wkJWQlABIb/B4zwIrVD5IH0D+qk3fS5J4FMATj/Os1IKz/HPseYvMP3KWc9enyAo4XlVTwRtLom2+82a5FwNVAR5EPmtrxW2qP1WiA7xlO/BMmnDiaPm+LArMLnuGGWqC2BT9mM3/BdrucdTtoOeZXhbwtFfXa1o4="
  file: "EternalPatcher"
  skip_cleanup: true
  on:
    tags: true