language: c
compiler: gcc

os: linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10
      - libcurl4-openssl-dev

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake .
  - make

deploy:
  provider: releases
  api_key:
    secure: "XAO8PrgTF6nuYPWh7iYZKeVyzY+sVVlTYvuBMHTuKDrXlgZNVkWB5v/5wmWhVa2WIPVTu3VNLGbUA0uWMPy5SAkecGb1j4apotYG2HegnlPju84wLDwdm8AMau7ZdTb2lsedY5B4Q2APdKvR5I9IiJAmqzLtfG/8kpTl0o4VAXSRhIUs49+9WQJ9SxdLvNpdQQpoc7U9ubMGG/py4YDeTpAO5TNIdUq1+L+jp2YbfXDfPRQ64gju5WydfdHeVYucBnkohnW2oYg6BKT6LXKPoaKjMKfQ1ZVMZX0dDV9vkHZm8NVf9aAX0nSu71t1E4ehs9QsZA3iwJSd5oBgLSgJlwIA9I9z1ZgyhNNlqKMbJ8aIQS0sC55RKZrt3igs+EmrU+x9lOT2gON+oPocevOcTcoSe9KhkyRpo8E58jnh21mX73rZ9eX826qLjWOCv6jOYj+bndpemes8dBvChNYIaHR5oJGXzX4sQsl3C9VLcXmLKr7SZwZ8UmX2JANkPVii7grdX2gEEAym3iXhqsD8rmieziOYIoT45d4dsy1XPVDL5OJBzGl1HvUFcrTEbjenKpIaJjSVesTAtre59EF+Vx5KBW6Q+qU+gGpfkr1npNJ+Zv/4JGSdmdh1cSEeA86wj//W1+1c30FejDPStLHT1wAeEk4VCXSUw6pZbTWH/UA="
  file: "EternalPatcher"
  skip_cleanup: true
  on:
    tags: true